apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  replicas: {{ .Values.elasticsearch.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Values.elasticsearch.name }}
    spec:
      # Elasticsearch uses memory map file system by default to store indices
      # Run busy-box to increase memory map count to 262144 (required)
      # This is not required on the Docker EE cluster
      # We also need to escalate Tiller service account to cluster admin in order to run 
      # with securityContext:privileged as true
      #initContainers:
      #- name: init-sysctl
      #  image: "{{ .Values.busybox.image.repository }}:{{ .Values.busybox.image.tag }}"
      #  imagePullPolicy: {{ .Values.busybox.image.pullPolicy }}
      #  command: ["sysctl", "-w", "vm.max_map_count=262144"]
      #  securityContext:
      #    privileged: true
      containers:
      - env:
        #- name: ES_JAVA_OPTS
        #  value: -Xms256m -Xms256m
        name: {{ .Values.elasticsearch.name }}
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        ports:
        - containerPort: {{ .Values.elasticsearch.containerPort }}