apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.kibana.name }}
spec:
  replicas: {{ .Values.kibana.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Values.kibana.name }}
    spec:
      containers:
      - name: {{ .Values.kibana.name }}
        image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
        ports:
        - containerPort: {{ .Values.kibana.containerPort }}
