apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.logstash.name }}
  labels:
    name: {{ .Values.logstash.name }}
spec:
  ports:
  - name: {{ .Values.logstash.name }}
    port: {{ .Values.logstash.port }}
    targetPort: {{ .Values.logstash.targetPort }}
  selector:
    name: {{ .Values.logstash.name }}