kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-test-claim
  namespace: ingress-traefik
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: testing