apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: ingress-traefik
data:
  traefik.toml: |
    # traefik.toml
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

    [acme]
    email = <email>
    storage = "/acme/acme.json"
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
    entryPoint = "https"
      [acme.dnsChallenge]
      provider = "gcloud"
      delayBeforeCheck = 300
      
    [[acme.domains]]
      main = <domain-name>
