apiVersion: v1
kind: Secret
metadata:
  name: proxy-secret
  namespace: ingress-traefik
type: Opaque
stringData:
  proxy: <proxy-address-if-needed>
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-secret
  namespace: ingress-traefik
type: Opaque
stringData:
  dns-secret.json: |-
    {
      "type": "service_account",
      "project_id": ,
      "private_key_id": ,
      "private_key": ,
      "client_email": ,
      "client_id": ,
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": 
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-env-secret
  namespace: ingress-traefik
type: Opaque
stringData:
  GCE_PROJECT: <project-name>
  GCE_SERVICE_ACCOUNT_FILE: /dns-config/dns-secret.json
